---

# plenv.yml
- name: Update pkgs
  apt: update_cache=yes

- name: Upgrade pkgs
  apt: upgrade=full

- name: Install git
  apt: pkg=git force=yes update_cache=yes


- name: Install perlenv
  script: perl/plenv.sh
  sudo: yes
  sudo_user: vagrant




